name: copyAndReplaceFile

on: 
  workflow_dispatch:
        
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Hello ${{ github.event.inputs.name }}!"
            - name: checkout repo content
              uses: actions/checkout@v2  # checkout the repository content to github runner
    
    copyImPlayer:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: copyImPlayer
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: ./tsImplayer.m3u
          dst_path: ./tsImplayerCopied.m3u
          dst_owner: jvpatil
          dst_repo_name: Channels
          dst_branch: master
          src_branch: master

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "|Content-Type=application/octet-stream|R{SSM}|"
          replace: " "
          include: "tsImplayerCopied.m3u"
          regex: false
  
    replaceString:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: replace
        uses: Nambers/ReplaceStringInFile@v1
        with:
          path: ${{ github.workspace }}/tsImplayerCopied.m3u
          oldString: \|Content-Type=application/octet-stream|R{SSM}|
          oldStringWin: \|Content-Type=application/octet-stream|R{SSM}|
          newString: ' '
          showFileContent: true
    
