name: copyAndReplaceFile

on: 
  workflow_dispatch:
        
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Hello ${{ github.event.inputs.name }}!"
            - name: checkout repo content
              uses: actions/checkout@v2  # checkout the repository content to github runner
    
    copyImPlayer:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: copyImPlayer
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: ./tsImplayer.m3u
          dst_path: ./tsImplayerCopied.m3u
          dst_owner: jvpatil
          dst_repo_name: Channels
          dst_branch: master
          src_branch: master

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "\\|.*$"
          replace: " "
          include: "tsImplayerCopied.mp3"
          regex: true
    
