name: Replace string in file

# on:
#   push:
#     branches:
#       - master
#       - main
on: 
  workflow_dispatch:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Replace string in file
        uses: MathieuSoysal/replace-string-in-file@v1.1.0
        with:
          file: tsImplayerCopied.m3u
          old-string: 'KODI'
          new-string: PODI
